version: '3.8'

services:
  treesearch-service:
    image: treesearch-service:latest
    container_name: treesearch-service
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - SCRAPER_SERVICE_URL=http://10.0.0.16:8001
    env_file:
      - .env
